Adicionar winston no projeto pra log
aceleradora-TW/sistema-de-votacao pull request #22
Opened 2018-04-03 20:30 UTC by ghidorsi

2018-04-03 20:59 UTC, yrachid approved these changes

2018-04-03 20:59 UTC, othman853 commented on src/server.js
> +const { winstonMiddleware } = require("./logger");
Sobraram uns `;` aqui. 

Podemos aproveitar para configurar o `eslint` para garantir linhas sem `;`? 

Assim, um `eslint --fix` já ajuda.

2018-04-03 21:16 UTC, ghidorsi commented on src/server.js
> +const { winstonMiddleware } = require("./logger");
oki doki

2018-04-03 21:37 UTC, yrachid requested changes

2018-04-03 21:37 UTC, othman853 commented on bin/cypress-run.js
> +      .catch(error => logger.info(error.message))
`logger.error`?

2018-04-03 21:37 UTC, othman853 commented on bin/test-server.js
> +  logger.info('Test server stopped')
Qual tipo de aspas vamos usar? Simples ou duplas? Voto nas aspas simples. 😄

2018-04-04 10:59 UTC, othman853 commented on bin/cypress-run.js
> +      .catch(error => logger.info(error.message))
Acredito que os eventos do Winston (info, warn, error, etc) possam receber objetos por parâmetro. 

O que aconteceria se tivéssemos, em vez de:

```javascript
.catch(error => logger.error(error)
```

Apenas:

```javascript
.catch(logger.error)
```

Além disso, o handler/callback passado para o `.catch` não tem parênteses em volta dos parâmetros. Que regra de linting vamos seguir neste caso? Deixamos os parâmetros ou tiramos?

2018-04-04 13:20 UTC, ghidorsi commented on bin/test-server.js
> +  logger.info('Test server stopped')
simples! padrão do eslint

2018-04-04 13:25 UTC, ghidorsi commented on bin/cypress-run.js
> +      .catch(error => logger.info(error.message))
A regra padrão do Eslint é não ter parenteses quando a funcão só tem um parametro, o que eu acho o correto.

2018-04-04 14:11 UTC, othman853 commented on bin/test-server.js
> +  logger.info('Test server stopped')
Sim, mas qual padrão do eslint vamos adotar? 

Nesse arquivo, existem aspas simples e aspas duplas ao mesmo tempo.

2018-04-04 14:51 UTC, yrachid approved these changes

2018-04-04 18:17 UTC, merged